[package]
name = "home_flow"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
log = "0.4"
egui = { version = "0.25.0", optional = true }
eframe = { version = "0.25.0", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
], optional = true }
serde = { version = "1.0.195", features = ["derive"] }
egui_plot = { version = "0.25.0", optional = true }

# WebAssembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.40"

# Server dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10.2"
axum = "0.7.4"
tokio = { version = "1.35.1", features = ["full"] }
tower-http = { version = "0.5.1", features = ["fs"] }

[features]
default = ["gui"]
gui = ["egui", "eframe", "egui_plot"]
