[package]
name = "home_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
anyhow = "1.0.79"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "js", "serde"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
toml = "0.8.10"
rayon = "1.8.1"
parking_lot = "0.12.1"
glam = { version = "0.25.0", features = ["serde"] }
strum = "0.26.1"
strum_macros = "0.26.1"
derivative = "2.2.0"
diff = "0.1.13"
image = { version = "0.24.8", default-features = false, features = ["png"] }
geo = "0.27.0"
geo-types = "0.7.12"
geo-buffer = { git = "https://github.com/CodedNil/geo-buffer" }
palette = { version = "0.7.4", default-features = false, features = ["std"] }

# GUI dependencies
egui = { version = "0.26.0", features = ["serde", "rayon"], optional = true }
egui_plot = { version = "0.26.0", optional = true }
ehttp = { version = "0.4.0", optional = true }
egui-notify = { version = "0.13.0", optional = true }
eframe = { version = "0.26.0", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
], optional = true }

# WebAssembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.41"

# Server dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simple_logger = "4.3.3"
axum = { version = "0.7.4", default-features = false, features = [
    "http1",
    "tokio",
    "json",
] }
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = [
    "fs",
    "compression-br",
    "compression-deflate",
    "compression-gzip",
] }
time = "0.3.34"

[features]
default = ["gui"]
gui = ["eframe", "egui", "egui_plot", "ehttp", "egui-notify"]

[profile.release]
lto = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
