[package]
name = "home_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
anyhow = "1.0.81"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "js", "serde"] }
serde = { version = "1.0.197", features = ["derive"] }
bincode = "1.3.3"
toml = "0.8.12"
parking_lot = "0.12.1"
indexmap = "2.2.6"
itertools = "0.12.1"
glam = { version = "0.27.0", features = ["serde"] }
strum = "0.26.2"
strum_macros = "0.26.2"
derivative = "2.2.0"
diff = "0.1.13"
image = { version = "0.25.1", default-features = false, features = ["png"] }
geo = "0.28.0"
geo-types = { version = "0.7.13", features = ["serde"] }

# GUI dependencies
egui = { version = "0.27.1", features = ["serde"], optional = true }
egui_plot = { version = "0.27.2", optional = true }
eframe = { version = "0.27.2", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
], optional = true }
egui-notify = { version = "0.14.0", optional = true }

# WebAssembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.69"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = [
    "console",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
] }

# Server dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simple_logger = "4.3.3"
axum = { version = "0.7.5", default-features = false, features = [
    "http1",
    "tokio",
] }
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = [
    "fs",
    "compression-br",
    "compression-deflate",
    "compression-gzip",
] }
time = "0.3.34"
geo-clipper = "0.8.0"

[features]
default = ["gui"]
gui = ["eframe", "egui", "egui_plot", "egui-notify"]

[profile.release]
lto = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
