[package]
name = "home_flow"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
log = "0.4.20"
anyhow = "1.0.79"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "js", "serde"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
once_cell = "1.19.0"
rayon = "1.8.1"
parking_lot = "0.12.1"
glam = { version = "0.25.0", features = ["serde"] }

strum = "0.26.1"
strum_macros = "0.26.1"
derivative = "2.2.0"
diff = "0.1.13"

# egui = { version = "0.25.0", features = ["serde"] }
egui = { git = "https://github.com/emilk/egui.git", rev = "9ae890dd1e217d5fd18760d6dd8860ea58bf165f", features = [
    "serde",
] }
egui_plot = "0.25.0"
ehttp = "0.4.0"
egui-notify = "0.12.0"
image = { version = "0.24", default-features = false, features = ["png"] }

geo = "0.27.0"
geo-types = "0.7.12"
geo-buffer = { git = "https://github.com/1011-git/geo-buffer.git", rev = "899c4dba1e0d8fdd99bd8ae1ce6efcaf482176a3" }
earcutr = "0.4.3"

# GUI dependencies
# eframe = { version = "0.25.0", default-features = false, features = [
#     "default_fonts",
#     "glow",
#     "persistence",
# ], optional = true }
eframe = { git = "https://github.com/emilk/egui.git", rev = "9ae890dd1e217d5fd18760d6dd8860ea58bf165f", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
], optional = true }

# WebAssembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.40"

# Server dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simple_logger = "4.3.3"
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = [
    "fs",
    "compression-br",
    "compression-deflate",
    "compression-gzip",
] }
chrono = "0.4.33"

[features]
default = ["gui"]
gui = ["eframe"]

[profile.release]
lto = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
