[package]
name = "home_flow"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
log = "0.4.20"
anyhow = "1.0.79"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
noise = "0.8.2"
once_cell = "1.19.0"

egui = { version = "0.25.0", optional = true }
image = { version = "0.24", optional = true }
eframe = { version = "0.25.0", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
], optional = true }
egui_plot = { version = "0.25.0", optional = true }
geo = "0.27.0"
geo-types = "0.7.12"
geo-booleanop = "0.3.2"

# WebAssembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.40"

# Server dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.0"
axum = "0.7.4"
tokio = { version = "1.35.1", features = ["full"] }
tower-http = { version = "0.5.1", features = [
    "fs",
    "compression-br",
    "compression-deflate",
    "compression-gzip",
] }

[features]
default = ["gui"]
gui = ["egui", "eframe", "egui_plot", "image"]
