name: Github Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build WASM
        run: ./trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"

      - name: Copy Wasm File
        run: cp dist/home_flow-*_bg.wasm dist/home_flow.wasm

      - name: Build Server
        run: cargo build --release --no-default-features --target-dir target/server --verbose

      - name: Copy Server File
        run: cp target/server/release/home_flow dist/home_flow_server

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
