name: Rust

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --no-default-features --target-dir target/server --verbose

      - name: Get Server Binary Size
        id: server-size
        run: echo "::set-output name=size::$(du -b target/server/home_flow | cut -f1)"

  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain with wasm target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}

      - name: Install trunk
        run: |
          if ! command -v trunk &> /dev/null
          then
            cargo install trunk
          fi

      - name: Build
        run: trunk build --release

      - name: Get Wasm File Size
        id: wasm-size
        run: echo "::set-output name=size::$(du -b dist/home_flow-*_bg.wasm | cut -f1)"

  update-readme:
    runs-on: ubuntu-latest
    needs: [build-server, build-wasm]
    steps:
      - uses: actions/checkout@v3

      - name: Update README with Binary Sizes
        run: python update_readme.py ${{ needs.build-server.outputs.server-size }} ${{ needs.build-wasm.outputs.wasm-size }}

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update binary sizes in README"
          git push
